// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1558943140);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1558943260);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558942779);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558942899);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1558943019);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1558943500);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1558943380);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 2);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 20);
user_pref("browser.download.lastDir", "/home/students/a/k/akkoyunl/Documents");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1551282100);
user_pref("browser.laterrun.bookkeeping.sessionCount", 12);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{fcd4894b-2f7e-4127-94e4-ddf9b2fcfed0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.setHomepage", "https://docs.iisg.agh.edu.pl/|about:newtab");
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558944582586");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558946363586");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558942756536");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558946356536");
user_pref("browser.search.region", "PL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190508134636");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1558942750");
user_pref("browser.slowStartup.averageTime", 1510);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190508134636");
user_pref("browser.startup.homepage_override.mstone", "66.0.5");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"ublock0_raymondhill_net-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.5");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "571089ad468d45619a983f401bf4fc5a");
user_pref("extensions.blocklist.lastModified", "Fri, 24 May 2019 15:52:25 GMT");
user_pref("extensions.blocklist.pingCountTotal", 18);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.databaseSchema", 30);
user_pref("extensions.getAddons.cache.lastUpdate", 1558943140);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190508134636");
user_pref("extensions.lastAppVersion", "66.0.5");
user_pref("extensions.lastPlatformVersion", "66.0.5");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{5c91bc01-abcb-4514-a83b-1a78d2a58443}\",\"addons\":{\"baidu-code-update@mozillaonline.com\":{\"version\":\"2.66\"},\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"50ced455-15ea-44ad-b606-71253fa7db07\",\"screenshots@mozilla.org\":\"5282eef4-8fb6-4741-8852-503639bd1a93\",\"webcompat-reporter@mozilla.org\":\"04f17ba7-d721-40a7-85c6-e001b05f9f3f\",\"webcompat@mozilla.org\":\"a4268576-224e-4292-94b7-8c2ef69e58cb\",\"uBlock0@raymondhill.net\":\"ef130f4b-77bb-4159-982f-7c0d951dcded\",\"fxmonitor@mozilla.org\":\"5a690cb4-d980-4b53-8424-33127536e1c1\",\"baidu-code-update@mozillaonline.com\":\"48ecd4a2-7932-4bad-b36f-5f8ba4b0a247\"}");
user_pref("idle.lastDailyNotification", 1558943008);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1554104366);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190508134636");
user_pref("media.gmp-manager.lastCheck", 1558942887);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1558338760);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "3a8ebfb6-19f9-4be9-8616-58d923469f8b");
user_pref("security.sandbox.plugin.tempDirSuffix", "0ef71832-6b4f-4807-a0d7-a0ed3f4ebdda");
user_pref("services.blocklist.addons.checked", 1558943052);
user_pref("services.blocklist.gfx.checked", 1558943052);
user_pref("services.blocklist.onecrl.checked", 1558943052);
user_pref("services.blocklist.pinning.checked", 1558943052);
user_pref("services.blocklist.plugins.checked", 1558943052);
user_pref("services.settings.clock_skew_seconds", -33);
user_pref("services.settings.last_etag", "\"1558915280627\"");
user_pref("services.settings.last_update_seconds", 1558943052);
user_pref("services.settings.main.language-dictionaries.last_check", 1558943052);
user_pref("services.settings.main.onboarding.last_check", 1558943052);
user_pref("services.settings.main.sites-classification.last_check", 1558943052);
user_pref("services.settings.main.tippytop.last_check", 1558943052);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1558338760);
user_pref("toolkit.startup.last_success", 1558942748);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20190508134636");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
